### ISSUE TITLE
Funny how you close this repo (somewhat) because I spammed your shitty webhook lol

### ISSUE THREAD

**Issue by something23-0001** [Cr6pt0/Innovatoz-Multitool#2]
Funny how you close this repo (somewhat) because I spammed your shitty webhook lol

**Comment by Cr6pt0** [comment]
How is that funny? I'll tell you something funny syn, you and you gay friend benny said that I was on your dick but you came back to me.

Anyways I do not care and I'll destroy benny's accounts. 
Cya

**Comment by Cr6pt0** [comment]
I didn't close bc of that but ok

**Comment by KDot227** [comment]
@Cr6pt0 I got 0 idea who @something23-0001 is but ik he right + ur a skid

**Comment by Cr6pt0** [comment]
ok
